### PR TITLE
fix: iframe overflows on mobile

### PR DESCRIPTION
**Pull request by i10416**
This hard-code width causes overflow on mobile.

### CODE REVIEW

**Comment by i10416** [comment]
note: some iframes inside span also cause overflow 🤔

**Comment by taisukeoe** [comment]
LGTM

**Comment by taisukeoe** [comment]
Hmm, this seems to corrupt PC version as show below...
Please let me revert this at this moment 🙏 

53b4bdd2a66a06524beb1dcd5e613447

**Comment by i10416** [comment]
@taisukeoe 

I overlooked that.  Sorry for the trouble.

**Pull request merged**
